openapi: "3.0.0"

info:
  description: "MediaWiki API"
  version: "0.1.0"
  title: "Wikipedia Media Wiki API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: https://{locale}.wikipedia.org
    variables:
      locale:
        default: en
        description: locale
paths:
  '/w/api.php':
    parameters:
      - name: User-Agent
        in: header
        required: true
        schema:
          type: string
          enum:
            - "Wikipedia4s/0.1.0 (https://github.com/ItoYo16u/wikipedia4s)"
      - name: "format"
        in: "query"
        description: "format"
        required: true
        schema:
          type: string
          enum:
            - json
      - name: "action"
        in: "query"
        description: "action"
        required: true
        schema:
          type: string
          enum:
            - query            
    get:
      summary: "request"
      description: "request"
      responses:
        200:
          description: "response on search success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
  /w/api.php/rest_v1/page/summary/{pagename}:
    get:
      summary: get page from page_name
      parameters:
        - in: path
          name: pagename
          schema:
            type: string
          required: true
components:
  schemas:
    SearchResponse:
      type: object
      required: 
        - query
      properties:
        query:
          type: object
          required:
            - searchinfo
            - search
          properties:
            searchinfo:
              type: object
              $ref: '#/components/schemas/SearchInfo'
            search:
              type: array
              items:
                $ref : '#/components/schemas/SearchResult'
    SearchResult:
      type: object
      required:
        - title
        - pageid
      properties:
        title:
          type: string
        pageid:
          type: integer
          format: int64
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - info
          properties:
            info:
              type: string
    SuggestResponse:
      type: object
      required:
        - query
      properties:
        query:
          type: object
          properties:
            searchinfo:
              type: object
              $ref: '#/components/schemas/SearchInfo'
    SearchInfo:
      type: object
      properties:
        suggestion:
          type: string
        totalhits:
          type: int

    GeoSearchResponse:
      type: object
      required:
        - query
      properties:
        query:
          type: object
          properties:
            geosearch:
              type: array
              items:
                $ref : '#/components/schemas/GeoSearchItem'
            pages:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/GeoSearchPages'
                  
    GeoSearchItem:
      type: object
      properties:
        title:
          type: string
        pageid:
          type: int
    GeoSearchPages:
      type: object
      properties:
        pageid:
          type: int
        ns:
          type: int
        title:
          type: string
        coordinates:
          type: array
          items:
            $ref: '#/components/schemas/GeoCoordinates'
    GeoCoordinates:
      type: object
      properties:
        lat:
          type: float
        lon:
          type: float
        primary:
          type: string
        globe:
          type: string
    SummaryResponse:
      type: object
      required:
        - query
      properties:
        query:
          type: object
          required:
            - pages
    MetaInfoResponse:
      type: object
      required:
        - query
      properties:
        query:
          type: object
          required:
           - general
          properties:
            general:
              type: object
              properties:
                mainpage:
                  type: string
                base:
                  type: string
                sitename:
                  type: string
                lang:
                  type: string
            languages:
              type: array
              items:
                $ref: '#/components/schemas/LanguageInfo'
            statistics:
              type: object
              properties:
                pages:
                  type: int
                articles:
                  type: int
                users:
                  type: int
                activeusers:
                  type: int
    LanguageInfo:
      type: object
      properties:
        code:
          type: string
        name:
          type: string

          
      

            
            
